### ISSUE TITLE
Enable 'database' to been pointed to other files as needed

### ISSUE THREAD

**Issue by philmmanjaro** [arkanelinux/arkdep#12]
Currently **arkdep** expects a file-server with folders to differentiate its variants. Example would be `arkdep/gnome/database` and `arkdep/plasma/database`. However, when you put s3 object storage into the mix you can only upload an image once. The primary differences between object and file storage are data structure and scalability. File storage is organized into hierarchy with directories and folders. File storage also follows strict file protocols, such as SMB, NFS, or Lustre. Object storage uses a flat structure with metadata and a unique identifier for each object that makes it easier to find among potentially billions of other objects.: https://aws.amazon.com/what-is/object-storage/

So I recommend to add some environment variable or function to define the name of the `database` file. This way you could add update channels for the same variant and test your image before a normal user would update to that image.

Since you can't move objects in a folder structure on object storage you have to remove the files and re-upload them to the new "folder structure". This will cost more bandwith and create unneeded workload, rather than just editing one simple text-file and purge that when a CDN is in use additionally.

**Comment by dennis1248** [comment]
Added in https://github.com/arkanelinux/arkdep/commit/b4f5befc078d5c1fce4229c6f74799f800710aa0
