### ISSUE TITLE
Arkdep and Arch Mirrors

### ISSUE THREAD

**Issue by celiopy** [arkanelinux/arkdep#13]
Ok, I'm not sure if this is related, and if this is the right place. But I've noticed that sometimes when I run arkdep-build with my list of packages, it sometimes have a good download speed (about 40MiB/s) and sometimes it fails under 900 Kib/s, why is that? How arkdep build selects the mirror? Usually on regular arch installs I get a stable_ish_ 40 MiB/s.

**Comment by dennis1248** [comment]
It defaults to the mirrors defined in the pacman.conf. The stock configs provided in the repo use a mirror in the Netherlands.

https://github.com/arkanelinux/arkdep/blob/main/arkdep-build.d/arkanelinux/pacman.conf#L80-L102

**Comment by celiopy** [comment]
> It uses to the mirrors defined in the pacman.conf. The stock configs provided in the repo use a mirror in the Netherlands.
> 
> The mirrors are hard coded to make the configs more portable, otherwise it may fail to build on systems lacking a mirrorlist file, or it may attempt to build against another distro.
> 
> https://github.com/arkanelinux/arkdep/blob/main/arkdep-build.d/arkanelinux/pacman.conf#L80-L102

I see, which means I shouldn't modify it? I changed pacman.conf in my custom, to make it download faster, it did, I didn't see no errors (kept arkane-related repos default), should I not do this?

Anyways, amazing work with this, and arkane! You can close this if you'd like.

**Comment by dennis1248** [comment]
> which means I shouldn't modify it?

You can safely modify it to use another Arch repo.

You could even swap it out with Manjaro, CachyOS or repos from other Arch-based distros, but it has no guarantee it will build successfully nor that the build images will work, this has not been extensively tested.


> Anyways, amazing work with this, and arkane!

Thanks!
