### ISSUE TITLE
Time zone changed to "London UK" after I updated my system

### ISSUE THREAD

**Issue by user1-github** [arkanelinux/arkdep#2]
Today I did my first update with "sudo arkdep deploy" and after reboot I noticed that the time displayed is wrong. In Gnome Settings I also found out that my time zone has changed to "London UK".

During Gnome initial setup I've disabled the location service, so maybe it would've kept the correct time zone if I had the service enabled.

But even if I have the location service disabled, the time zone that I've initially set should be kept after update.

**Comment by dennis1248** [comment]
I think I know why this happened. I recently switched over to using gnome-initial-setup for account and locale creation instead of doing this through os-installer.

gnome-initial-setup will configure the locale in `/etc`, but this is then later not backed up to `/arkdep/overlay`.

I will convert the `var_migrate_files` setting to no longer be `/var`-only and make it filesystem wide, so `/etc` stuff can also be backed up using it.

**Comment by user1-github** [comment]
Thanks, will try the workaround

**Comment by dennis1248** [comment]
This issue should now be fixed with https://github.com/arkanelinux/arkdep/commit/c07d34d3290a1dce9034eaeecf199ee27d383d4a

I am pushing a new image with this update as well.

You will have to run two updates before the change shows, the first update to the fixed version will still run with the old version of Arkdep.

Add this to `/arkdep/config`, otherwise it will yell at you during updates;

```
migrate_files=('/var/usrlocal' '/var/usrliblocale' '/var/opt' '/var/srv' '/var/nm-system-connections' '/var/lib/AccountsService' '/var/lib/bluetooth' '/var/lib/NetworkManager' '/var/lib/arkane' '/etc/localtime' '/etc/locale.gen' '/etc/locale.conf')
```

**Comment by user1-github** [comment]
> This issue should now be fixed with [c07d34d](https://github.com/arkanelinux/arkdep/commit/c07d34d3290a1dce9034eaeecf199ee27d383d4a)
> 
> I am pushing a new image with this update as well.
> 
> You will have to run two updates before the change shows, the first update to the fixed version will still run with the old version of Arkdep.
> 
> Add this to `/arkdep/config`, otherwise it will yell at you during updates;
> 
> ```
> migrate_files=('/var/usrlocal' '/var/usrliblocale' '/var/opt' '/var/srv' '/var/nm-system-connections' '/var/lib/AccountsService' '/var/lib/bluetooth' '/var/lib/NetworkManager' '/var/lib/arkane' '/etc/localtime' '/etc/locale.gen' '/etc/locale.conf')
> ```

Thanks. Might be a dumb question, but should I keep this line in /arkdep/config after I did the 2 updates?

**Comment by dennis1248** [comment]
> > This issue should now be fixed with [c07d34d](https://github.com/arkanelinux/arkdep/commit/c07d34d3290a1dce9034eaeecf199ee27d383d4a)
> > I am pushing a new image with this update as well.
> > You will have to run two updates before the change shows, the first update to the fixed version will still run with the old version of Arkdep.
> > Add this to `/arkdep/config`, otherwise it will yell at you during updates;
> > ```
> > migrate_files=('/var/usrlocal' '/var/usrliblocale' '/var/opt' '/var/srv' '/var/nm-system-connections' '/var/lib/AccountsService' '/var/lib/bluetooth' '/var/lib/NetworkManager' '/var/lib/arkane' '/etc/localtime' '/etc/locale.gen' '/etc/locale.conf')
> > ```
> 
> Thanks. Might be a dumb question, but should I keep this line in /arkdep/config after I did the 2 updates?

You can either remove it to clean it up, or keep it as such. The migration runs after the overlay is copied and will overwrite whatever is stored in the overlay.

**Comment by user1-github** [comment]
> You can either remove it to clean it up, or keep it as such. The migration runs after the overlay is copied and will overwrite whatever is stored in the overlay.

Thanks again. I think if in the future Arkdep will have such change/s again that will require to modify /arkdep/config or any other file, it would be a good idea to mention it in [Arkdep patch notes](https://docs.arkanelinux.org/patch_notes/arkdep/) so that everyone will see.

**Comment by dennis1248** [comment]
> > You can either remove it to clean it up, or keep it as such. The migration runs after the overlay is copied and will overwrite whatever is stored in the overlay.
> 
> Thanks again. I think if in the future Arkdep will have such change/s again that will require to modify /arkdep/config or any other file, it would be a good idea to mention it in [Arkdep patch notes](https://docs.arkanelinux.org/patch_notes/arkdep/) so that everyone will see.
> 
> Edit: I was just reading about Arkdep config file in the docs so I understood that some Arkdep behaviors are considered "optional". Is "migrate_files=" considered an optional behavior? If yes then I assume it should be left in the config file for the migration of user accounts, time zone, etc to work properly, at least as long as it's considered an optional behavior.

All settings currently in the config file are required. If they are not defined Arkdep will instead run them with default settings hardcoded in to the script.

To disable migrate_files you can give it an empty list, but this is something you typically do not want to do except in some edgecases maybe.
